kind: pipeline
type: kubernetes
name: default

steps:
  -
    name: lint and test
    image: golang:1.23
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
      - golangci-lint run ./...
      - go test -cover ./...
  
  -
    name: build and release
    image: docker:dind
    environment:
      GHCR_USERNAME:
        from_secret: ghcr_username
      GHCR_PASSWORD:
        from_secret: ghcr_password
    commands:
      - docker login --username $GHCR_USERNAME --password $GHCR_PASSWORD ghcr.io
      - docker build -t ghcr.io/ravenxwrx/chainkills:$(git rev-parse --short HEAD) .