kind: pipeline
type: kubernetes
name: default

steps:
  -
    name: lint and test
    image: golang:1.23
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
      - golangci-lint run ./...
      - go test -cover ./...