kind: pipeline
type: kubernetes
name: default

steps:
  -
    name: lint and test
    image: golang:1.23
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.0.2
      - golangci-lint run ./...
      - go test -cover ./...
  
  -
    name: build and release
    image: docker:dind
    environment:
      ghcr_username:
        from_secret: ghcr_username
      ghcr_password:
        from_secret: ghcr_password
    commands:
      - echo $GHCR_USERNAME
      - echo $GHCR_PASSWORD
      # - docker login --username ${GHCR_USERNAME} --password ${GHCR_PASSWORD} ghcr.io