admin_name: Hi
admin_email: hello@admin.com
app_name: ItsMe
version: v0.1.0
refresh_interval: 300
wanderer:
  token: 
  slug: 
  host: https://wanderer.ltd
only_wh_kills: true
ignore_systems:
  - Jita
  - Thera
discord:
  token: 
  channel: 
friends:
  alliances: []
  corporations: []
  characters: []
redis:
  address: localhost:6379
  database: 0