apiVersion: v1
kind: ConfigMap
metadata:
  name: chainkills-config
data:
  config.yaml: |
    admin_name: Hi
    admin_email: hello@admin.com
    app_name: ItsMe
    version: v0.1.0
    refresh_interval: 300
    wanderer:
      token: 
      slug: 
      host: https://wanderer.ltd
    only_wh_kills: true
    ignore_systems:
      - Jita
      - Thera
    discord:
      token: 
      channel: 
    friends:
      alliances: []
      corporations: []
      characters: []
    redis:
      address: chainkills-redict-svc:6379
      database: 0
      ttl: 1440
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chainkills-redict-config
data:
  redict.conf: |
    dir /var/data
    appendonly yes
    loglevel verbose
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chainkills-app-env
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
  OTEL_EXPORTER_OTLP_INSECURE: "true"
