apiVersion: v1
kind: ConfigMap
metadata:
  name: chainkills-config
data:
  config.yaml: |
    admin_name: Hi
    app_name: ItsMe
    version: v0.1.0
    refresh_interval: 60
    wanderer:
      token: 
      slug: 
      host: https://wanderer.ltd
    only_wh_kills: true
    ignore_systems:
      - Jita
      - Thera
    discord:
      token: 
      channel: 
    friends:
      alliances: []
      corporations: []
      characters: []
    redis:
      address: chainkills-redict-svc:6379
      database: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chainkills-redict-config
data:
  redict.conf: |
    dir /var/data
    appendonly yes
    loglevel verbose
