apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainkills
spec:
  selector:
    matchLabels:
      app: chainkills
  template:
    metadata:
      labels:
        app: chainkills
    spec:
      containers:
        - name: chainkills
          image: ghcr.io/alfreddobradi/chainkills:v0.7.1-pre.9
          command:
            - 'chainkills'
            - '--config'
            - '/etc/chainkills/config.yaml'
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: chainkills-app-env
          volumeMounts:
            - name: config
              mountPath: "/etc/chainkills"
              readOnly: true
        - name: redict
          image: registry.redict.io/redict:bookworm
          command:
            - "redict-server"
            - "/etc/redict/redict.conf"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: "/var/data"
              name: redict-pvc
            - mountPath: "/etc/redict"
              name: redict-config
          ports:
            - containerPort: 6379
      securityContext:
        fsGroup: 999
      volumes:
        - name: config
          configMap:
            name: chainkills-config
        - name: redict-config
          configMap:
            name: chainkills-redict-config
        - name: redict-pvc
          persistentVolumeClaim:
            claimName: chainkills-redict-claim
