apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chainkills-redict-claim
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi